version: '3'
services:
    receiver:
        build: ./Receive
        restart: always
        links:
            - rabbitmq
            - database
        networks:
            - network 
    database:
        image: postgres
        restart: always
        environment: 
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_NAME = postgres
            - POSTGRES_USER = postgres
        networks:
            - network
    rabbitmq: 
        image: rabbitmq:3
        restart: always
        hostname: my-rabbit
        networks: 
            - network
networks:
    network:
